# Generated by Django 2.2.4 on 2019-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=512)),
                ('amount_money', models.DecimalField(decimal_places=1, max_digits=19)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
