# Generated by Django 2.2.4 on 2019-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0002_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.IntegerField()),
                ('sex', models.IntegerField(default=0, verbose_name=1)),
                ('nickname', models.CharField(max_length=12)),
                ('passport', models.IntegerField(verbose_name=21)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('amount_money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('introduction', models.CharField(max_length=512)),
                ('isexpired', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
