# Generated by Django 2.2.4 on 2019-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0005_shopping_cart_isselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='NULL', max_length=12),
        ),
    ]
