# Generated by Django 2.2.4 on 2019-09-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0006_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport',
            field=models.CharField(max_length=18),
        ),
    ]
