# Generated by Django 2.2.4 on 2019-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0007_auto_20190903_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('content', models.CharField(max_length=512)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
