# Generated by Django 2.2.4 on 2019-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0008_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='picUrl1',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='picUrl2',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='picUrl3',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='picUrl4',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
