# Generated by Django 2.2.4 on 2019-09-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0009_auto_20190904_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
