# Generated by Django 2.2.4 on 2019-09-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0011_auto_20190905_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaints',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food_category',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
