# Generated by Django 2.2.4 on 2019-09-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0012_auto_20190909_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='isDelete',
            new_name='isdeleted',
        ),
    ]
