# Generated by Django 2.2.4 on 2019-09-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0013_auto_20190909_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone',
            field=models.IntegerField(verbose_name=12),
        ),
        migrations.AlterField(
            model_name='food',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='stop_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
