# Generated by Django 2.2.4 on 2019-09-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0015_auto_20190911_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone',
            field=models.BigIntegerField(verbose_name=20),
        ),
    ]
