# Generated by Django 2.2.4 on 2019-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end_app', '0016_auto_20190911_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='remarks',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
